spring.application.name=skillbridge
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/SkillBridge
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update