spring.application.name=skillbridge
server.port=${PORT:8082}

spring.datasource.url=jdbc:postgresql://localhost:5432/SkillBridge
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=e3trvtvyt6tyuju9j9yrcxx345678hbtcfvfcdxxcvybtvt8990jhh